# Generated by Django 4.2.7 on 2023-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Models',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('my_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('agree', models.BooleanField(default=False)),
                ('binaryfield', models.BinaryField(blank=True)),
            ],
        ),
    ]
